name: JRuby snapshot using Java 21

on: workflow_dispatch
permissions:
  contents: read

jobs:
  publish:
    permissions:
      contents: read
    uses: jruby/jruby/.github/workflows/snapshot-publish.yml@46678ce513443c231ce91c7782ad72b886aed5b4
    with:
      javaLevel: 21
    secrets:
      SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
      SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
