name: JRuby snapshot deploy

on: workflow_dispatch
permissions:
  contents: read

jobs:
  publish:
    permissions:
      contents: none
    uses: jruby/jruby/.github/workflows/snapshot-publish.yml@ff01541350b9767a4b47e6b46181649d6a316fc6
    secrets:
      SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
      SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
