name: JRuby snapshot using Java 21

on: workflow_dispatch
permissions:
  contents: read

jobs:
  publish:
    permissions:
      contents: read
    uses: jruby/jruby/.github/workflows/snapshot-publish.yml@5c281bb7db572a7ecbbb88fa7bd3e31253837291
    with:
      javaLevel: 21
    secrets:
      SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
      SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
