name: JRuby snapshot deploy

on: workflow_dispatch
permissions:
  contents: read

jobs:
  publish:
    permissions:
      contents: read
    uses: jruby/jruby/.github/workflows/snapshot-publish.yml@f5b000d735c993bd3d3af27e6241f6c83565bbaa
    secrets:
      SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
      SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
