name: Nightly Snapshots using Java 21

on:
  schedule:
    - cron: '30 6 * * *'

env:
  JAVA_OPTS: '-XX:+TieredCompilation -XX:TieredStopAtLevel=1 -Xms60M -Xmx1G -XX:InitialCodeCacheSize=40M -XX:ReservedCodeCacheSize=120M'

permissions:
  contents: read

jobs:
  publish-snapshot:
    permissions:
      contents: read
    if: ${{ github.ref == 'refs/heads/master' && github.repository == 'jruby/jruby' }}
    uses: jruby/jruby/.github/workflows/snapshot-publish.yml@d8369e218d4878b79d394a90483f109a2096a820
    with:
      javaLevel: 21
    secrets:
      SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
      SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
