name: Nightly Snapshots using Java 8

on:
  schedule:
    - cron: '30 6 * * *'

env:
  JAVA_OPTS: '-XX:+TieredCompilation -XX:TieredStopAtLevel=1 -Xms60M -Xmx1G -XX:InitialCodeCacheSize=40M -XX:ReservedCodeCacheSize=120M'

permissions:
  contents: read

jobs:
  publish-snapshot:
    permissions:
      contents: none
    if: ${{ github.ref == 'refs/heads/master' || github.ref == 'refs/heads/jruby-9.4' }}
    uses: jruby/jruby/.github/workflows/snapshot-publish.yml@6e8a7c652c75755032d344e4ac2b236ec37c77b0
    with:
      javaLevel: 8
    secrets:
      SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
      SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
